services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      HOSTNAME: 0.0.0.0
    networks:
      - default
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
